### ISSUE TITLE
vLLM v0.17.1+ container images failing on GKE

### ISSUE THREAD

**Issue by jtechapps** [llm-d/llm-d#1063]
When replacing the container image with an image build `ghcr.io/llm-d/llm-d-cuda-dev:sha-ce75a09` containing the changes for bumping vLLM version to v0.17.1, vLLM crashes with the following error:

```
(EngineCore_DP14 pid=883) (Worker pid=939) (Worker_DP14_EP14 pid=939) ERROR 03-18 06:29:32 [multiproc_executor.py:800] torch._inductor.exc.InductorError: CalledProcessError: Command '['/usr/bin/gcc', '/tmp/tmpm4i7fy2q/cuda_utils.c', '-O3', '-shared', '-fPIC', '-Wno-psabi', '-o', '/tmp/tmpm4i7fy2q/cuda_utils.cpython-312-x86_64-linux-gnu.so', '-l:libcuda.so.1', '-L/opt/vllm/lib/python3.12/site-packages/triton/backends/nvidia/lib', '-L/usr/lib64', '-I/opt/vllm/lib/python3.12/site-packages/triton/backends/nvidia/include', '-I/tmp/tmpm4i7fy2q', '-I/usr/include/python3.12']' returned non-zero exit status 1.
```

```
/usr/bin/ld: cannot find -l:libcuda.so.1
collect2: error: ld returned 1 exit status
```

When SSHing into the container before it crashes and checking the paths:
```
$ kubectl exec --stdin --tty -n $NAMESPACE wide-ep-llm-d-decode-0 -- /bin/bash
Defaulted container "vllm" out of: vllm, routing-proxy (init)
bash-5.1# find /usr/ -name 'libcuda.so.1'
/usr/local/nvidia/lib64/libcuda.so.1
/usr/local/cuda-12.9/compat/libcuda.so.1
bash-5.1# find /usr/ -name 'libcuda.so.1'
/usr/local/nvidia/lib64/libcuda.so.1
/usr/local/cuda-12.9/compat/libcuda.so.1
bash-5.1# echo $LD_LIBRARY_PATH
/opt/vllm/lib64/python3.12/site-packages/torch/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64/stubs:/usr/local/cuda/lib64:/opt/amazon/efa/lib:/opt/amazon/efa/lib64:/opt/ucx/lib:/opt/ucx/lib64:/opt/nvshmem-v3.4.5-0/lib:/opt/nvshmem-v3.4.5-0/lib64:/usr/local/lib:/usr/local/lib64:/usr/lib/x86_64-linux-gnu:/usr/lib/aarch64-linux-gnu:/usr/local/cuda/lib64
```

Container images built with older vLLM do not run into this issue such as `ghcr.io/llm-d/llm-d-cuda:v0.5.1` do not run into this error.

**Comment by nekoteai** [comment]
in my scenaro, /usr/local/nvidia/lib64 is empty and /usr/lib/x86_64-linux-gnu contains capab libcuda file

**Comment by ianliuy** [comment]
## What's broken?

vLLM containers built with vLLM v0.17.1+ crash on GKE at startup with:
```
/usr/bin/ld: cannot find -l:libcuda.so.1
```
Torch inductor's JIT compilation (`gcc`) fails because the compile-time linker cannot find `libcuda.so.1`.

## Who is affected?

Anyone running llm-d CUDA container images on GKE (or other environments where the NVIDIA driver is mounted at runtime by the NVIDIA Container Toolkit into `/usr/local/nvidia/lib64/`). Older images with vLLM < 0.17.1 are not affected.

## When does it trigger?

Consistently on container startup when vLLM initializes workers and torch inductor JIT-compiles CUDA utilities. Workaround confirmed by @jtechapps and @rlakhtakia: `export LIBRARY_PATH=/usr/local/nvidia/lib64:$LIBRARY_PATH` before starting vLLM.

## Where is the bug?

`docker/Dockerfile.cuda` — the **runtime stage** (line ~288+):
- `LD_LIBRARY_PATH` is set (line 325–334) covering runtime dynamic loading ✅
- `LIBRARY_PATH` is **not set** — the compile-time linker has no search paths ❌
- `ldconfig` is **never run** in the runtime stage — the linker cache is stale ❌

The builder stage (line 249–251) correctly has both `ld.so.conf.d` entries and `ldconfig`, but this doesn't carry over to the runtime stage.

## Why does it happen?

PR #606 switched the runtime base image from `cuda:*-devel-*` to `cuda:*-runtime-*` to reduce image size. The `-devel` image included CUDA stubs that the linker could find; `-runtime` does not. Subsequently, PR #727 removed `${CUDA_HOME}/compat` from `LD_LIBRARY_PATH` to avoid error 803 from loading stub drivers at runtime.

The key distinction: `LD_LIBRARY_PATH` is for the **runtime** dynamic linker (`ld.so`), while `LIBRARY_PATH` is for the **compile-time** static linker (`/usr/bin/ld` invoked by `gcc -l:`). The Dockerfile sets the former but not the latter.

When torch inductor JIT-compiles `cuda_utils.c` with `gcc -l:libcuda.so.1`, the compile-time linker searches:
1. `-L` paths (triton dir, `/usr/lib64`) — no `libcuda.so.1` here
2. `LIBRARY_PATH` env var — **not set**
3. `ldconfig` cache (`/etc/ld.so.cache`) — **never rebuilt** in runtime stage

All three miss → `cannot find -l:libcuda.so.1`.

## How did we fix it?

Two changes in the runtime stage of `docker/Dockerfile.cuda`:

1. **Add `LIBRARY_PATH` to the ENV block** — exposes NVIDIA runtime-injected paths (`/usr/local/nvidia/lib64/`) and CUDA toolkit paths to the compile-time linker. These paths mirror those already in `LD_LIBRARY_PATH`.

2. **Add `ld.so.conf.d` + `ldconfig` after library COPYs** — mirrors builder stage lines 249–251 exactly. Rebuilds the linker cache so libraries copied from the builder (gdrcopy, UCX, NVSHMEM, NIXL) are properly registered. Pattern already used in `Dockerfile.rdma-tools` line 118.

Both changes have direct precedent in the same repo — no new patterns introduced.

## How do we know it works?

Will be filled after implementation.

---

Fixes #1063. I'm working on a fix.

**Comment by ianliuy** [comment]
Implemented as described above. PR: https://github.com/llm-d/llm-d/pull/1147
